---
- name: Setup New VMs
  hosts: ubuntu_servers
  become: true

  vars:
    mysql_root_password: "your_root_secure_password" # Ganti dengan password root yang diinginkan
    mysql_user: "newuser" # Ganti dengan username yang diinginkan
    mysql_user_password: "your_secure_user_password" # Ganti dengan password user yang diinginkan

  tasks:
    - name: Update and Upgrade APT packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install basic utilities
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - vim
          - git
        state: present

    - name: Install OpenSSH server
      ansible.builtin.apt:
        name: openssh-server
        state: present

    - name: Install MySQL server
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true

    - name: Set the MySQL root password
      ansible.builtin.mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        state: present

    - name: Remove anonymous users
      ansible.builtin.mysql_user:
        name: ""
        host: localhost
        state: absent

    - name: Remove test database
      ansible.builtin.mysql_db:
        name: test
        state: absent

    - name: Create a new MySQL user
      ansible.builtin.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        host: localhost
        state: present
        privileges: "*.*:ALL" # Memberikan semua hak akses ke semua database

    - name: Reload privileges table
      ansible.builtin.command: >
        mysql -u root -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES;"
